spring:
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  mail:
    host: ${EMAIL_HOST}
    port: 587
    username: ${EMAIL_USER}
    password: ${EMAIL_APP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  jwtSecret: ======================expense=tracker=mywallet===========================
  jwtExpirationMs: 86400000
  verificationCodeExpirationMs: 900000
  user:
    profile:
      upload:
        dir: ./uploads/user/profile
