CREATE SEQUENCE IF NOT EXISTS budget_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS saved_transaction_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE budget
(
    budget_id BIGINT           NOT NULL,
    user_id   BIGINT           NOT NULL,
    amount    DOUBLE PRECISION NOT NULL,
    month     INTEGER          NOT NULL,
    year      BIGINT           NOT NULL,
    CONSTRAINT pk_budget PRIMARY KEY (budget_id)
);

CREATE TABLE category
(
    category_id         INTEGER NOT NULL,
    category_name       VARCHAR(255),
    transaction_type_id INTEGER,
    enabled             BOOLEAN NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (category_id)
);

CREATE TABLE roles
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(20),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE saved_transaction
(
    plan_id             BIGINT           NOT NULL,
    user_id             BIGINT           NOT NULL,
    transaction_type_id INTEGER          NOT NULL,
    category_id         INTEGER          NOT NULL,
    amount              DOUBLE PRECISION NOT NULL,
    description         VARCHAR(255),
    frequency           VARCHAR(255),
    upcoming_date       date,
    CONSTRAINT pk_savedtransaction PRIMARY KEY (plan_id)
);

CREATE TABLE transaction
(
    transaction_id BIGINT           NOT NULL,
    user_id        BIGINT,
    category_id    INTEGER,
    description    VARCHAR(255),
    amount         DOUBLE PRECISION NOT NULL,
    date           date,
    CONSTRAINT pk_transaction PRIMARY KEY (transaction_id)
);

CREATE TABLE transaction_type
(
    transaction_type_id   INTEGER NOT NULL,
    transaction_type_name VARCHAR(20),
    CONSTRAINT pk_transactiontype PRIMARY KEY (transaction_type_id)
);

CREATE TABLE user_roles
(
    role_id INTEGER NOT NULL,
    user_id BIGINT  NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE users
(
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username                      VARCHAR(20),
    email                         VARCHAR(255),
    password                      VARCHAR(255),
    verification_code             VARCHAR(64),
    verification_code_expiry_time TIMESTAMP WITHOUT TIME ZONE,
    enabled                       BOOLEAN                                 NOT NULL,
    profile_img_url               VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_74165e195b2f7b25de690d14a UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_77584fbe74cc86922be2a3560 UNIQUE (username);

ALTER TABLE category
    ADD CONSTRAINT FK_CATEGORY_ON_TRANSACTIONTYPEID FOREIGN KEY (transaction_type_id) REFERENCES transaction_type (transaction_type_id);

ALTER TABLE transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_CATEGORYID FOREIGN KEY (category_id) REFERENCES category (category_id);

ALTER TABLE transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_USERID FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id);