CREATE SEQUENCE IF NOT EXISTS savings_goal_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS reward_seq START WITH 1 INCREMENT BY 50;

-- Create savings_goal table
CREATE TABLE savings_goal (
    goal_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    target_amount DOUBLE PRECISION NOT NULL,
    current_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    start_date DATE NOT NULL,
    target_date DATE,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    category_id INTEGER,
    CONSTRAINT pk_savings_goal PRIMARY KEY (goal_id)
);

-- Create reward table
CREATE TABLE reward (
    reward_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    points_required INTEGER NOT NULL,
    is_redeemed BOOLEAN NOT NULL DEFAULT FALSE,
    created_date DATE NOT NULL,
    redeemed_date DATE,
    CONSTRAINT pk_reward PRIMARY KEY (reward_id)
);

-- Create user_points table to track user reward points
CREATE TABLE user_points (
    user_id BIGINT NOT NULL,
    points INTEGER NOT NULL DEFAULT 0,
    last_updated TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user_points PRIMARY KEY (user_id)
);

-- Create savings_contribution table to track contributions to savings goals
CREATE TABLE savings_contribution (
    contribution_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    goal_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    contribution_date DATE NOT NULL,
    transaction_id BIGINT,
    CONSTRAINT pk_savings_contribution PRIMARY KEY (contribution_id)
);

-- Add foreign key constraints
ALTER TABLE savings_goal
    ADD CONSTRAINT FK_SAVINGS_GOAL_ON_USERID FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE savings_goal
    ADD CONSTRAINT FK_SAVINGS_GOAL_ON_CATEGORYID FOREIGN KEY (category_id) REFERENCES category (category_id);

ALTER TABLE reward
    ADD CONSTRAINT FK_REWARD_ON_USERID FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_points
    ADD CONSTRAINT FK_USER_POINTS_ON_USERID FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE savings_contribution
    ADD CONSTRAINT FK_SAVINGS_CONTRIBUTION_ON_GOALID FOREIGN KEY (goal_id) REFERENCES savings_goal (goal_id);

ALTER TABLE savings_contribution
    ADD CONSTRAINT FK_SAVINGS_CONTRIBUTION_ON_USERID FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE savings_contribution
    ADD CONSTRAINT FK_SAVINGS_CONTRIBUTION_ON_TRANSACTIONID FOREIGN KEY (transaction_id) REFERENCES transaction (transaction_id);